// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Yol.Punla.UnitTest.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class PostFeedDetailsPageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "PostFeedDetailsPage.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PostFeedDetailsPage", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "PostFeedDetailsPage")))
            {
                global::Yol.Punla.UnitTest.Tests.PostFeedDetailsPageFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Navigating to PostFeedDetailsPage Then Back")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PostFeedDetailsPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FacebookLogonViaWriteYourThoughtsMenu")]
        public virtual void NavigatingToPostFeedDetailsPageThenBack()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating to PostFeedDetailsPage Then Back", new string[] {
                        "tag",
                        "FacebookLogonViaWriteYourThoughtsMenu"});
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given("I am authenticated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
  testRunner.And("I am on the page \"PostFeedPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 7
  testRunner.And("I could see that the IsNavigatingDetailsPage mark is \"false\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
 testRunner.When("I tap the comment icon of the post of \"Peter Smith\" with content \"Mental health i" +
                    "s now on the final reading in the Congress. Sen. Riza Hotiveros pushes the bill." +
                    "\" and postFeedId \"1112\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.Then("I am redirected to the page \"PostFeedDetailPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
  testRunner.And("I can see the details of the post with author \"Peter Smith\" and content \"Mental h" +
                    "ealth is now on the final reading in the Congress. Sen. Riza Hotiveros pushes th" +
                    "e bill.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
  testRunner.And("I could see that the IsNavigatingDetailsPage mark is \"true\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.When("I tap the back icon from PostFeedDetailsPage", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 13
 testRunner.Then("I am redirected to the page \"PostFeedPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 14
  testRunner.And("I could see that the IsNavigatingDetailsPage mark is \"false\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void AddingCommentsToAPost(string comment, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "tag",
                    "FacebookLogonViaWriteYourThoughtsMenu"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding Comments to a post", @__tags);
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I am authenticated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
  testRunner.And("I am on the page \"PostFeedPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.When("I tap the comment icon of the post of \"Peter Smith\" with content \"Mental health i" +
                    "s now on the final reading in the Congress. Sen. Riza Hotiveros pushes the bill." +
                    "\" and postFeedId \"1112\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
 testRunner.Then("I am redirected to the page \"PostFeedDetailPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 22
  testRunner.And("I can see the details of the post with author \"Peter Smith\" and content \"Mental h" +
                    "ealth is now on the final reading in the Congress. Sen. Riza Hotiveros pushes th" +
                    "e bill.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 23
 testRunner.When(string.Format("I type comment \"{0}\" and tap the Post button", comment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 24
 testRunner.Then("I should stay on the same page \"PostFeedDetailPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding Comments to a post: Hello, This is a comment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PostFeedDetailsPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FacebookLogonViaWriteYourThoughtsMenu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("VariantName", "Hello, This is a comment")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:comment", "Hello, This is a comment")]
        public virtual void AddingCommentsToAPost_HelloThisIsAComment()
        {
#line 17
this.AddingCommentsToAPost("Hello, This is a comment", ((string[])(null)));
#line hidden
        }
        
        public virtual void AddingEmptyCommentToAPost(string comment, string errorMessage, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "tag",
                    "FacebookLogonViaWriteYourThoughtsMenu"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding Empty comment to a post", @__tags);
#line 31
this.ScenarioSetup(scenarioInfo);
#line 32
 testRunner.Given("I am authenticated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
  testRunner.And("I am on the page \"PostFeedPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.When("I tap the comment icon of the post of \"Peter Smith\" with content \"Mental health i" +
                    "s now on the final reading in the Congress. Sen. Riza Hotiveros pushes the bill." +
                    "\" and postFeedId \"1112\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 35
 testRunner.Then("I am redirected to the page \"PostFeedDetailPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 36
  testRunner.And("I can see the details of the post with author \"Peter Smith\" and content \"Mental h" +
                    "ealth is now on the final reading in the Congress. Sen. Riza Hotiveros pushes th" +
                    "e bill.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.When(string.Format("I type comment \"{0}\" and tap the Post button", comment), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 38
 testRunner.Then(string.Format("I should see an empty comment message \"{0}\"", errorMessage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Adding Empty comment to a post: ")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "PostFeedDetailsPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("FacebookLogonViaWriteYourThoughtsMenu")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:comment", "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("Parameter:errorMessage", "Empty comment is not allowed. Please write a comment.")]
        public virtual void AddingEmptyCommentToAPost_()
        {
#line 31
this.AddingEmptyCommentToAPost("", "Empty comment is not allowed. Please write a comment.", ((string[])(null)));
#line hidden
        }
    }
}
#pragma warning restore
#endregion
