// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Yol.Punla.UnitTest.Tests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class WelcomeInstructionPageFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "WelcomeInstructionPage.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "WelcomeInstructionPage", "\tThis is the first page the user will be \r\n\tnavigated to when he / she run the ap" +
                    "p\r\n\tfor the first time.\r\n\r\n\tRunning again the app after that will not\r\n\tnavigate" +
                    " the user to the WelcomeInstructionPage\r\n\tagain.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "WelcomeInstructionPage")))
            {
                global::Yol.Punla.UnitTest.Tests.WelcomeInstructionPageFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(TestContext);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Running the app for the first time")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WelcomeInstructionPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WelcomeInstructionIsNotLoadedYet")]
        public virtual void RunningTheAppForTheFirstTime()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Running the app for the first time", new string[] {
                        "tag",
                        "WelcomeInstructionIsNotLoadedYet"});
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
 testRunner.Given("I am not authenticated", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 13
  testRunner.And("I am on the page \"WelcomeInstructionsPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
 testRunner.Then("I should see the back arrow of the page grayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 15
  testRunner.And("I should see the instruction text \"You could post your feelings anonymously. When" +
                    " you post only your alias is shown.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Navigating to the second page of the instructions page")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WelcomeInstructionPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WelcomeInstructionIsNotLoadedYet")]
        public virtual void NavigatingToTheSecondPageOfTheInstructionsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating to the second page of the instructions page", new string[] {
                        "tag",
                        "WelcomeInstructionIsNotLoadedYet"});
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
 testRunner.Given("I am on the page \"WelcomeInstructionsPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
  testRunner.And("I could see the instruction text \"You could post your feelings anonymously. When " +
                    "you post only your alias is shown.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
  testRunner.And("the back button is grayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.When("I tap the forward arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("I should see the instruction text \"If you wish to see a local psychologist or psy" +
                    "chiatrist, you could browse the mental care facilities section. You could sort t" +
                    "hem by location and, you could also call their tel nos straight away.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 24
  testRunner.And("I should see the back button is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Navigating back to the previous instruction page from last instruction")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WelcomeInstructionPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WelcomeInstructionIsNotLoadedYet")]
        public virtual void NavigatingBackToThePreviousInstructionPageFromLastInstruction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating back to the previous instruction page from last instruction", new string[] {
                        "tag",
                        "WelcomeInstructionIsNotLoadedYet"});
#line 27
this.ScenarioSetup(scenarioInfo);
#line 28
 testRunner.Given("I am on the page \"WelcomeInstructionsPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 29
  testRunner.And("I could see the instruction text \"You could post your feelings anonymously. When " +
                    "you post only your alias is shown.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
  testRunner.And("I should see the back arrow of the page grayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("I tap the forward arrow three times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.Then("I should see the instruction text \"Signing up with facebook or signing up with al" +
                    "iasname only are provided. Your privacy and data security is our top priority.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 33
 testRunner.When("I tap the back arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 34
 testRunner.Then("I should see the instruction text \"If you are in crisis or your family or friends" +
                    ", you can browse to the directory of crisis providers section. You could easily " +
                    "tap and call their tel nos.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 35
  testRunner.And("I should see the back button is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Navigating back to the previous instruction page from third instruction")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WelcomeInstructionPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WelcomeInstructionIsNotLoadedYet")]
        public virtual void NavigatingBackToThePreviousInstructionPageFromThirdInstruction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating back to the previous instruction page from third instruction", new string[] {
                        "tag",
                        "WelcomeInstructionIsNotLoadedYet"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
 testRunner.Given("I am on the page \"WelcomeInstructionsPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 40
  testRunner.And("I could see the instruction text \"You could post your feelings anonymously. When " +
                    "you post only your alias is shown.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
  testRunner.And("I should see the back arrow of the page grayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 42
 testRunner.When("I tap the forward arrow two times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 43
 testRunner.Then("I should see the instruction text \"If you are in crisis or your family or friends" +
                    ", you can browse to the directory of crisis providers section. You could easily " +
                    "tap and call their tel nos.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 44
 testRunner.When("I tap the back arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
 testRunner.Then("I should see the instruction text \"If you wish to see a local psychologist or psy" +
                    "chiatrist, you could browse the mental care facilities section. You could sort t" +
                    "hem by location and, you could also call their tel nos straight away.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 46
  testRunner.And("I should see the back button is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Navigating back to the previous instruction page from second instruction")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WelcomeInstructionPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WelcomeInstructionIsNotLoadedYet")]
        public virtual void NavigatingBackToThePreviousInstructionPageFromSecondInstruction()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating back to the previous instruction page from second instruction", new string[] {
                        "tag",
                        "WelcomeInstructionIsNotLoadedYet"});
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
 testRunner.Given("I am on the page \"WelcomeInstructionsPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 51
  testRunner.And("I could see the instruction text \"You could post your feelings anonymously. When " +
                    "you post only your alias is shown.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
  testRunner.And("I should see the back arrow of the page grayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 53
 testRunner.When("I tap the forward arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 54
 testRunner.Then("I should see the instruction text \"If you wish to see a local psychologist or psy" +
                    "chiatrist, you could browse the mental care facilities section. You could sort t" +
                    "hem by location and, you could also call their tel nos straight away.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 55
 testRunner.When("I tap the back arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 56
 testRunner.Then("I should see the instruction text \"You could post your feelings anonymously. When" +
                    " you post only your alias is shown.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 57
  testRunner.And("I should see the back arrow of the page grayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Navigating to WikiPage via tapping the forward arrow in the last instruction text" +
            "")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "WelcomeInstructionPage")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("tag")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("WelcomeInstructionIsNotLoadedYet")]
        public virtual void NavigatingToWikiPageViaTappingTheForwardArrowInTheLastInstructionText()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Navigating to WikiPage via tapping the forward arrow in the last instruction text" +
                    "", new string[] {
                        "tag",
                        "WelcomeInstructionIsNotLoadedYet"});
#line 60
this.ScenarioSetup(scenarioInfo);
#line 61
 testRunner.Given("I am on the page \"WelcomeInstructionsPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 62
  testRunner.And("I could see the instruction text \"You could post your feelings anonymously. When " +
                    "you post only your alias is shown.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 63
  testRunner.And("I should see the back arrow of the page grayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 64
 testRunner.When("I tap the forward arrow three times", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 65
 testRunner.Then("I should see the instruction text \"Signing up with facebook or signing up with al" +
                    "iasname only are provided. Your privacy and data security is our top priority.\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 66
  testRunner.And("I should see the back button is enabled", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.When("I tap the forward arrow", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.Then("I am redirected to the page \"WikiPage\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
