//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yol.Punla.Localized {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yol.Punla.Localized.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AccountAlready {
            get {
                return ResourceManager.GetString("AccountAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Someone to encourage you.
        /// </summary>
        public static string ActiveCarousel {
            get {
                return ResourceManager.GetString("ActiveCarousel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to HopePH Alpha version. Some of the features are not yet activated in this version..
        /// </summary>
        public static string AdMessage {
            get {
                return ResourceManager.GetString("AdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This message requires action. Apology for the inconvenience..
        /// </summary>
        public static string AdMessageRequiresAttention {
            get {
                return ResourceManager.GetString("AdMessageRequiresAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string AliasText {
            get {
                return ResourceManager.GetString("AliasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pangga Health.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticating your credentials. Please wait....
        /// </summary>
        public static string AuthenticatingCredentialsLoadingText {
            get {
                return ResourceManager.GetString("AuthenticatingCredentialsLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your avatar.
        /// </summary>
        public static string AvatarChoiceText {
            get {
                return ResourceManager.GetString("AvatarChoiceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        public static string CallString {
            get {
                return ResourceManager.GetString("CallString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE PHOTO.
        /// </summary>
        public static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a comment....
        /// </summary>
        public static string CommentPlaceholderText {
            get {
                return ResourceManager.GetString("CommentPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder to everyone.
        /// </summary>
        public static string CrisisHotlineReminder {
            get {
                return ResourceManager.GetString("CrisisHotlineReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crisis Hotlines.
        /// </summary>
        public static string CrisisHotlines {
            get {
                return ResourceManager.GetString("CrisisHotlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting your comment....
        /// </summary>
        public static string DeletingComment {
            get {
                return ResourceManager.GetString("DeletingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting your post wasnt successful. Please try again!.
        /// </summary>
        public static string DeletingPostNotSuccessful {
            get {
                return ResourceManager.GetString("DeletingPostNotSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depression can happen to anyone and does happen to one in four of us over our lifetimes. Different factors that make it more likely to happen, include biological make-up, upbringing, or reaction to life events. What keeps it going though, is how we deal with those things. The way we think and what we do affects the way we feel. Depression is often accompanied by other feelings such as guilt, shame anger and anxiety..
        /// </summary>
        public static string DepressionBlurb {
            get {
                return ResourceManager.GetString("DepressionBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account yet?.
        /// </summary>
        public static string DontHaveAccountYetText {
            get {
                return ResourceManager.GetString("DontHaveAccountYetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account already exists. Please use login instead..
        /// </summary>
        public static string DuplicateSignUpBlurb {
            get {
                return ResourceManager.GetString("DuplicateSignUpBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email already exists..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty comment is not allowed. Please write a comment..
        /// </summary>
        public static string EmptyCommentErrorMessage {
            get {
                return ResourceManager.GetString("EmptyCommentErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting with empty content is not allowed..
        /// </summary>
        public static string EmptyPostErrorMessage {
            get {
                return ResourceManager.GetString("EmptyPostErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string EnterAValidEmailText {
            get {
                return ResourceManager.GetString("EnterAValidEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please download the latest version.
        /// </summary>
        public static string ForceUpdateMessage {
            get {
                return ResourceManager.GetString("ForceUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullNameText {
            get {
                return ResourceManager.GetString("FullNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the hamburger menu at the top left corner to browse our menu..
        /// </summary>
        public static string HamburgerMenuClicked {
            get {
                return ResourceManager.GetString("HamburgerMenuClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching comments for the first time might take a while. Please wait while we cache the data....
        /// </summary>
        public static string LoadingComments {
            get {
                return ResourceManager.GetString("LoadingComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading for the first time might take a while. Please wait while we cache the data....
        /// </summary>
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching data from the server. Please wait....
        /// </summary>
        public static string LoadingDataOrig {
            get {
                return ResourceManager.GetString("LoadingDataOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! There was an error in the uploading of the post feed. Please try again..
        /// </summary>
        public static string LoadingErrorPostFeed {
            get {
                return ResourceManager.GetString("LoadingErrorPostFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching more posts from the server. Please wait....
        /// </summary>
        public static string LoadingMoreData {
            get {
                return ResourceManager.GetString("LoadingMoreData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching notifications from the server. Please wait....
        /// </summary>
        public static string LoadingNotifications {
            get {
                return ResourceManager.GetString("LoadingNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while we load your own posts....
        /// </summary>
        public static string LoadingOwnData {
            get {
                return ResourceManager.GetString("LoadingOwnData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with.
        /// </summary>
        public static string LoginWithText {
            get {
                return ResourceManager.GetString("LoginWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll need a verification code to sign in to the app. Please enter your registered email..
        /// </summary>
        public static string LogonContentCode {
            get {
                return ResourceManager.GetString("LogonContentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent you a verification code..
        /// </summary>
        public static string LogonContentVerify {
            get {
                return ResourceManager.GetString("LogonContentVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong username or password please try again..
        /// </summary>
        public static string LogonIncorrect {
            get {
                return ResourceManager.GetString("LogonIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code Request.
        /// </summary>
        public static string LogonTitleCode {
            get {
                return ResourceManager.GetString("LogonTitleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your verification code.
        /// </summary>
        public static string LogonTitleVerify {
            get {
                return ResourceManager.GetString("LogonTitleVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with username.
        /// </summary>
        public static string LogonWithUserName {
            get {
                return ResourceManager.GetString("LogonWithUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin feugiat luctus posuere. Sed scelerisque, purus ultricies consequat pellentesque, est magna aliquet mi, id tincidunt arcu enim id tellus. Nam gravida risus at enim lacinia, a imperdiet libero commodo. Fusce eget neque id augue rutrum aliquet ut aliquam tortor. Nunc sit amet quam sodales, auctor dui quis, posuere est. Sed et elit vitae sem porttitor blandit a eu nunc. Curabitur tempus dui tincidunt metus pretium feugiat. Mauris ullamcorper nulla m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoremIpsumText {
            get {
                return ResourceManager.GetString("LoremIpsumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Care Facilities.
        /// </summary>
        public static string MentalCareFacilities {
            get {
                return ResourceManager.GetString("MentalCareFacilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the hamburger menu at the top left corner to browse our menu..
        /// </summary>
        public static string MenuClicked {
            get {
                return ResourceManager.GetString("MenuClicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        public static string MobilePhoneText {
            get {
                return ResourceManager.GetString("MobilePhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 unread comment to this post.
        /// </summary>
        public static string NotificationsHasUnReadComments {
            get {
                return ResourceManager.GetString("NotificationsHasUnReadComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please show support or care by clicking support or by writing friendly advises to.
        /// </summary>
        public static string NotificationsShowSupport {
            get {
                return ResourceManager.GetString("NotificationsShowSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change photo is not supported by this version of the app. Please wait for our next version..
        /// </summary>
        public static string NotSupportedChangePhoto {
            get {
                return ResourceManager.GetString("NotSupportedChangePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by rating and specializations are not supported by this version of the app. Please wait for our next version..
        /// </summary>
        public static string NotSupportedRatingAndSpecializations {
            get {
                return ResourceManager.GetString("NotSupportedRatingAndSpecializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings is not yet available by this version of the app. Please wait for our next version..
        /// </summary>
        public static string NotSupportedSettings {
            get {
                return ResourceManager.GetString("NotSupportedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by rating is not supported by this version of the app. Please wait for our next version..
        /// </summary>
        public static string NotSupportedSortByRating {
            get {
                return ResourceManager.GetString("NotSupportedSortByRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any post.
        /// </summary>
        public static string PostingReminder {
            get {
                return ResourceManager.GetString("PostingReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostText {
            get {
                return ResourceManager.GetString("PostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading post....
        /// </summary>
        public static string PostUploading {
            get {
                return ResourceManager.GetString("PostUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When needed, you could pull down to refresh posts from the server :).
        /// </summary>
        public static string PullDownInstruction {
            get {
                return ResourceManager.GetString("PullDownInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string ReplyText {
            get {
                return ResourceManager.GetString("ReplyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing your request. Please wait....
        /// </summary>
        public static string RequestProcessingLoadingText {
            get {
                return ResourceManager.GetString("RequestProcessingLoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires signing up.
        /// </summary>
        public static string RequiresSignUp {
            get {
                return ResourceManager.GetString("RequiresSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Function is available for the next version..
        /// </summary>
        public static string SearchAvailableNextVersionText {
            get {
                return ResourceManager.GetString("SearchAvailableNextVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share an article, photo, video or idea.
        /// </summary>
        public static string SharePostText {
            get {
                return ResourceManager.GetString("SharePostText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please signup. Signing up wont display your profile to the other users. You will still maintain your anonymity..
        /// </summary>
        public static string SignUpMessage {
            get {
                return ResourceManager.GetString("SignUpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup..
        /// </summary>
        public static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with aliasname.
        /// </summary>
        public static string SignUpWithUserName {
            get {
                return ResourceManager.GetString("SignUpWithUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a sort item..
        /// </summary>
        public static string SortSelect {
            get {
                return ResourceManager.GetString("SortSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporters.
        /// </summary>
        public static string SupportersText {
            get {
                return ResourceManager.GetString("SupportersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental heath support group and services..
        /// </summary>
        public static string TagLine {
            get {
                return ResourceManager.GetString("TagLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map or Call.
        /// </summary>
        public static string TitleCall {
            get {
                return ResourceManager.GetString("TitleCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your Comments.
        /// </summary>
        public static string TitleComments {
            get {
                return ResourceManager.GetString("TitleComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write down your thoughts or feelings.
        /// </summary>
        public static string TitleFeelings {
            get {
                return ResourceManager.GetString("TitleFeelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contents &amp; Details.
        /// </summary>
        public static string TitleReadContents {
            get {
                return ResourceManager.GetString("TitleReadContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Settings.
        /// </summary>
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Thoughts &amp; Feelings.
        /// </summary>
        public static string TitleThoughts {
            get {
                return ResourceManager.GetString("TitleThoughts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Stuff.
        /// </summary>
        public static string UsefulStuff {
            get {
                return ResourceManager.GetString("UsefulStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid verification code.
        /// </summary>
        public static string VerficationCodeError {
            get {
                return ResourceManager.GetString("VerficationCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need to know how to contact you.
        /// </summary>
        public static string VerificationEmailMsg {
            get {
                return ResourceManager.GetString("VerificationEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string VerificationEmailPlaceholder {
            get {
                return ResourceManager.GetString("VerificationEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string VerificationEmailTitle {
            get {
                return ResourceManager.GetString("VerificationEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We sent the verification code in your email.
        /// </summary>
        public static string VerifiedEmailMsg {
            get {
                return ResourceManager.GetString("VerifiedEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        public static string VerifiedEmailPlaceholder {
            get {
                return ResourceManager.GetString("VerifiedEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your verification code.
        /// </summary>
        public static string VerifiedEmailTitle {
            get {
                return ResourceManager.GetString("VerifiedEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map.
        /// </summary>
        public static string ViewMapText {
            get {
                return ResourceManager.GetString("ViewMapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Down What You Want to Say.
        /// </summary>
        public static string WDWYWTS {
            get {
                return ResourceManager.GetString("WDWYWTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You could post your feelings anonymously. No one knows you here..
        /// </summary>
        public static string WelcomeInstructions1 {
            get {
                return ResourceManager.GetString("WelcomeInstructions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you wish to see a local psychologist or psychiatrist, you could browse the mental care facilities and sort them by location and check their tel nos and location..
        /// </summary>
        public static string WelcomeInstructions2 {
            get {
                return ResourceManager.GetString("WelcomeInstructions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string WelcomeInstructions3 {
            get {
                return ResourceManager.GetString("WelcomeInstructions3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string WelcomeInstructions4 {
            get {
                return ResourceManager.GetString("WelcomeInstructions4", resourceCulture);
            }
        }
    }
}
