//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yol.Punla.Localized {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings_fil {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings_fil() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Yol.Punla.Localized.AppStrings.fil", typeof(AppStrings_fil).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AccountAlready {
            get {
                return ResourceManager.GetString("AccountAlready", resourceCulture);
            }
        }
        
        public static string ActiveCarousel {
            get {
                return ResourceManager.GetString("ActiveCarousel", resourceCulture);
            }
        }
        
        public static string AdMessage {
            get {
                return ResourceManager.GetString("AdMessage", resourceCulture);
            }
        }
        
        public static string AdMessageRequiresAttention {
            get {
                return ResourceManager.GetString("AdMessageRequiresAttention", resourceCulture);
            }
        }
        
        public static string AliasText {
            get {
                return ResourceManager.GetString("AliasText", resourceCulture);
            }
        }
        
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        public static string AuthenticatingCredentialsLoadingText {
            get {
                return ResourceManager.GetString("AuthenticatingCredentialsLoadingText", resourceCulture);
            }
        }
        
        public static string AvatarChoiceText {
            get {
                return ResourceManager.GetString("AvatarChoiceText", resourceCulture);
            }
        }
        
        public static string CallString {
            get {
                return ResourceManager.GetString("CallString", resourceCulture);
            }
        }
        
        public static string ChangePhoto {
            get {
                return ResourceManager.GetString("ChangePhoto", resourceCulture);
            }
        }
        
        public static string CommentPlaceholderText {
            get {
                return ResourceManager.GetString("CommentPlaceholderText", resourceCulture);
            }
        }
        
        public static string CommentText {
            get {
                return ResourceManager.GetString("CommentText", resourceCulture);
            }
        }
        
        public static string CrisisHotlineReminder {
            get {
                return ResourceManager.GetString("CrisisHotlineReminder", resourceCulture);
            }
        }
        
        public static string CrisisHotlines {
            get {
                return ResourceManager.GetString("CrisisHotlines", resourceCulture);
            }
        }
        
        public static string DeletingComment {
            get {
                return ResourceManager.GetString("DeletingComment", resourceCulture);
            }
        }
        
        public static string DeletingPostNotSuccessful {
            get {
                return ResourceManager.GetString("DeletingPostNotSuccessful", resourceCulture);
            }
        }
        
        public static string DepressionBlurb {
            get {
                return ResourceManager.GetString("DepressionBlurb", resourceCulture);
            }
        }
        
        public static string DontHaveAccountYetText {
            get {
                return ResourceManager.GetString("DontHaveAccountYetText", resourceCulture);
            }
        }
        
        public static string DuplicateSignUpBlurb {
            get {
                return ResourceManager.GetString("DuplicateSignUpBlurb", resourceCulture);
            }
        }
        
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        public static string EmptyCommentErrorMessage {
            get {
                return ResourceManager.GetString("EmptyCommentErrorMessage", resourceCulture);
            }
        }
        
        public static string EmptyPostErrorMessage {
            get {
                return ResourceManager.GetString("EmptyPostErrorMessage", resourceCulture);
            }
        }
        
        public static string EnterAValidEmailText {
            get {
                return ResourceManager.GetString("EnterAValidEmailText", resourceCulture);
            }
        }
        
        public static string ForceUpdateMessage {
            get {
                return ResourceManager.GetString("ForceUpdateMessage", resourceCulture);
            }
        }
        
        public static string FullNameText {
            get {
                return ResourceManager.GetString("FullNameText", resourceCulture);
            }
        }
        
        public static string HamburgerMenuClicked {
            get {
                return ResourceManager.GetString("HamburgerMenuClicked", resourceCulture);
            }
        }
        
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        public static string LoadingComments {
            get {
                return ResourceManager.GetString("LoadingComments", resourceCulture);
            }
        }
        
        public static string LoadingData {
            get {
                return ResourceManager.GetString("LoadingData", resourceCulture);
            }
        }
        
        public static string LoadingErrorPostFeed {
            get {
                return ResourceManager.GetString("LoadingErrorPostFeed", resourceCulture);
            }
        }
        
        public static string LoadingOwnData {
            get {
                return ResourceManager.GetString("LoadingOwnData", resourceCulture);
            }
        }
        
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        public static string LoginWithText {
            get {
                return ResourceManager.GetString("LoginWithText", resourceCulture);
            }
        }
        
        public static string LogonIncorrect {
            get {
                return ResourceManager.GetString("LogonIncorrect", resourceCulture);
            }
        }
        
        public static string LoremIpsumText {
            get {
                return ResourceManager.GetString("LoremIpsumText", resourceCulture);
            }
        }
        
        public static string MentalCareFacilities {
            get {
                return ResourceManager.GetString("MentalCareFacilities", resourceCulture);
            }
        }
        
        public static string MobilePhoneText {
            get {
                return ResourceManager.GetString("MobilePhoneText", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string NotSupportedChangePhoto {
            get {
                return ResourceManager.GetString("NotSupportedChangePhoto", resourceCulture);
            }
        }
        
        public static string NotSupportedRatingAndSpecializations {
            get {
                return ResourceManager.GetString("NotSupportedRatingAndSpecializations", resourceCulture);
            }
        }
        
        public static string NotSupportedSettings {
            get {
                return ResourceManager.GetString("NotSupportedSettings", resourceCulture);
            }
        }
        
        public static string NotSupportedSortByRating {
            get {
                return ResourceManager.GetString("NotSupportedSortByRating", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string PasswordText {
            get {
                return ResourceManager.GetString("PasswordText", resourceCulture);
            }
        }
        
        public static string PostingReminder {
            get {
                return ResourceManager.GetString("PostingReminder", resourceCulture);
            }
        }
        
        public static string PostText {
            get {
                return ResourceManager.GetString("PostText", resourceCulture);
            }
        }
        
        public static string PostUploading {
            get {
                return ResourceManager.GetString("PostUploading", resourceCulture);
            }
        }
        
        public static string PullDownInstruction {
            get {
                return ResourceManager.GetString("PullDownInstruction", resourceCulture);
            }
        }
        
        public static string ReplyText {
            get {
                return ResourceManager.GetString("ReplyText", resourceCulture);
            }
        }
        
        public static string RequestProcessingLoadingText {
            get {
                return ResourceManager.GetString("RequestProcessingLoadingText", resourceCulture);
            }
        }
        
        public static string RequiresSignUp {
            get {
                return ResourceManager.GetString("RequiresSignUp", resourceCulture);
            }
        }
        
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        public static string SearchAvailableNextVersionText {
            get {
                return ResourceManager.GetString("SearchAvailableNextVersionText", resourceCulture);
            }
        }
        
        public static string SharePostText {
            get {
                return ResourceManager.GetString("SharePostText", resourceCulture);
            }
        }
        
        public static string ShareText {
            get {
                return ResourceManager.GetString("ShareText", resourceCulture);
            }
        }
        
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        public static string SignUpMessage {
            get {
                return ResourceManager.GetString("SignUpMessage", resourceCulture);
            }
        }
        
        public static string SignUpText {
            get {
                return ResourceManager.GetString("SignUpText", resourceCulture);
            }
        }
        
        public static string SortSelect {
            get {
                return ResourceManager.GetString("SortSelect", resourceCulture);
            }
        }
        
        public static string SupportersText {
            get {
                return ResourceManager.GetString("SupportersText", resourceCulture);
            }
        }
        
        public static string SupportText {
            get {
                return ResourceManager.GetString("SupportText", resourceCulture);
            }
        }
        
        public static string TagLine {
            get {
                return ResourceManager.GetString("TagLine", resourceCulture);
            }
        }
        
        public static string TitleCall {
            get {
                return ResourceManager.GetString("TitleCall", resourceCulture);
            }
        }
        
        public static string TitleComments {
            get {
                return ResourceManager.GetString("TitleComments", resourceCulture);
            }
        }
        
        public static string TitleFeelings {
            get {
                return ResourceManager.GetString("TitleFeelings", resourceCulture);
            }
        }
        
        public static string TitleReadContents {
            get {
                return ResourceManager.GetString("TitleReadContents", resourceCulture);
            }
        }
        
        public static string TitleSettings {
            get {
                return ResourceManager.GetString("TitleSettings", resourceCulture);
            }
        }
        
        public static string TitleThoughts {
            get {
                return ResourceManager.GetString("TitleThoughts", resourceCulture);
            }
        }
        
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        public static string UsefulStuff {
            get {
                return ResourceManager.GetString("UsefulStuff", resourceCulture);
            }
        }
        
        public static string UsernameText {
            get {
                return ResourceManager.GetString("UsernameText", resourceCulture);
            }
        }
        
        public static string ViewMapText {
            get {
                return ResourceManager.GetString("ViewMapText", resourceCulture);
            }
        }
        
        public static string WDWYWTS {
            get {
                return ResourceManager.GetString("WDWYWTS", resourceCulture);
            }
        }
        
        public static string WelcomeInstructions1 {
            get {
                return ResourceManager.GetString("WelcomeInstructions1", resourceCulture);
            }
        }
        
        public static string WelcomeInstructions2 {
            get {
                return ResourceManager.GetString("WelcomeInstructions2", resourceCulture);
            }
        }
        
        public static string WelcomeInstructions3 {
            get {
                return ResourceManager.GetString("WelcomeInstructions3", resourceCulture);
            }
        }
        
        public static string WelcomeInstructions4 {
            get {
                return ResourceManager.GetString("WelcomeInstructions4", resourceCulture);
            }
        }
        
        public static string SignUpWithUserName {
            get {
                return ResourceManager.GetString("SignUpWithUserName", resourceCulture);
            }
        }
        
        public static string VerficationCodeError {
            get {
                return ResourceManager.GetString("VerficationCodeError", resourceCulture);
            }
        }
        
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        public static string VerificationEmailMsg {
            get {
                return ResourceManager.GetString("VerificationEmailMsg", resourceCulture);
            }
        }
        
        public static string VerificationEmailPlaceholder {
            get {
                return ResourceManager.GetString("VerificationEmailPlaceholder", resourceCulture);
            }
        }
        
        public static string VerificationEmailTitle {
            get {
                return ResourceManager.GetString("VerificationEmailTitle", resourceCulture);
            }
        }
        
        public static string VerifiedEmailMsg {
            get {
                return ResourceManager.GetString("VerifiedEmailMsg", resourceCulture);
            }
        }
        
        public static string VerifiedEmailPlaceholder {
            get {
                return ResourceManager.GetString("VerifiedEmailPlaceholder", resourceCulture);
            }
        }
        
        public static string VerifiedEmailTitle {
            get {
                return ResourceManager.GetString("VerifiedEmailTitle", resourceCulture);
            }
        }
    }
}
